# Generated by Django 5.0.3 on 2024-03-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=13)),
                ('profession', models.CharField(max_length=250)),
                ('residence', models.CharField(max_length=250)),
                ('mstatus', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorce', 'divorce'), ('widow(er)', 'widow(er)')], default='married', max_length=10)),
            ],
        ),
    ]
