# Generated by Django 5.0.3 on 2024-03-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notice',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
